name: Create Release

on:
  push:
    tags:
    - 'v*'

release:
  name: Create Release
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secretes.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false